package darthorimar.intellijcbt.project

import com.intellij.openapi.externalSystem.service.settings.AbstractExternalSystemToolWindowCondition

class CbtToolWindowFactoryCondition
  extends AbstractExternalSystemToolWindowCondition(CbtProjectSystem.Id)