package darthorimar.intellijcbt.project.settings

import com.intellij.openapi.externalSystem.settings.ExternalSystemSettingsListener

trait CbtProjectSettingsListener extends ExternalSystemSettingsListener[CbtProjectSettings]
